import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  // Watch-mode rebuilds must not wipe dist/, since build:css (tokens.css,
  // fonts.css, ...) only runs once and isn't regenerated by tsup itself.
  clean: !process.argv.includes("--watch"),
});
